# Generated by Django 5.1.5 on 2025-02-12 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_profile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adoption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('behavior', models.TextField(blank=True, null=True)),
                ('rescue_story', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='dogs/')),
            ],
        ),
    ]
