# Generated by Django 5.1.5 on 2025-02-13 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturedTestimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('feedback', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.feedback')),
            ],
        ),
    ]
