# Generated by Django 5.1.5 on 2025-02-13 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_featuredtestimonial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FeaturedTestimonial',
        ),
    ]
