# Generated by Django 5.1.5 on 2025-02-15 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_remove_adoption_is_available_adoptionrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='adoption',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.DeleteModel(
            name='AdoptionRequest',
        ),
    ]
