# Generated by Django 5.1.5 on 2025-02-16 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_adoptionrequest_unique_pending_approved_dog'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='adoptionrequest',
            name='unique_pending_approved_dog',
        ),
    ]
