# Generated by Django 5.1.5 on 2025-02-16 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_remove_adoptionrequest_unique_pending_approved_dog'),
    ]

    operations = [
        migrations.AddField(
            model_name='adoption',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.DeleteModel(
            name='AdoptionRequest',
        ),
    ]
