# Generated by Django 5.1.5 on 2025-02-17 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_adoptionrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adoption',
            name='is_available',
        ),
        migrations.DeleteModel(
            name='AdoptionRequest',
        ),
    ]
