# Generated by Django 5.1.5 on 2025-02-22 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_alter_adoptionrequest_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='booked_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
