# Generated by Django 5.1.5 on 2025-02-22 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_feedback_booked_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='booked_date',
        ),
    ]
