# Generated by Django 5.1.5 on 2025-02-22 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_rescueimage_rescuereport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rescuereport',
            name='images',
        ),
        migrations.RemoveField(
            model_name='rescuereport',
            name='user',
        ),
        migrations.DeleteModel(
            name='RescueImage',
        ),
        migrations.DeleteModel(
            name='RescueReport',
        ),
    ]
