# Generated by Django 5.1.5 on 2025-03-01 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0031_alter_rescuerequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='adoptionrequest',
            name='adoption_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
