# Generated by Django 5.1.5 on 2025-03-01 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0032_adoptionrequest_adoption_reason'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adoptionrequest',
            name='adoption_reason',
        ),
    ]
