# Generated by Django 5.1.5 on 2025-03-27 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0039_remove_appointment_unique_appointment_slot_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ['-date', 'time']},
        ),
        migrations.AlterField(
            model_name='appointment',
            name='allergies',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='current_medications',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='medical_history',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='special_notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
