# Generated by Django 5.1.5 on 2025-03-29 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0043_alter_appointment_allergies_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ['-date', '-time']},
        ),
        migrations.AlterUniqueTogether(
            name='appointment',
            unique_together={('date', 'time')},
        ),
    ]
