# Generated by Django 5.1.5 on 2025-03-29 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0044_alter_appointment_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='appointment',
            unique_together=set(),
        ),
    ]
