# Generated by Django 5.1.5 on 2025-03-30 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0046_appointment_unique_time_slot_per_date'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='appointment',
            name='unique_time_slot_per_date',
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'cancelled'), _negated=True), fields=('date', 'time'), name='unique_time_slot_per_date'),
        ),
    ]
