# Generated by Django 5.1.5 on 2025-03-30 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0047_remove_appointment_unique_time_slot_per_date_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='appointment',
            name='unique_time_slot_per_date',
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.UniqueConstraint(fields=('date', 'time'), name='unique_time_slot_per_date'),
        ),
    ]
