# Generated by Django 5.1.3 on 2025-04-07 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0051_donation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Donation',
        ),
    ]
