# Generated by Django 5.1.3 on 2025-04-08 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0053_donation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Donation',
        ),
    ]
