# Generated by Django 5.1.3 on 2025-04-17 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0056_dogimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DogImage',
        ),
    ]
