# Generated by Django 5.1.3 on 2025-04-17 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0060_remove_adoption_image_dogimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='adoption',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='dogs/'),
        ),
        migrations.DeleteModel(
            name='DogImage',
        ),
    ]
